version: '3.8'

services:
  primary_db:
    image: postgres:15
    container_name: postgres_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pampered_pets_development
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    networks:
      - backend

  queue_db:
    image: postgres:15
    container_name: postgres_queue
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pampered_pets_development_queue
    volumes:
      - postgres_queue_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_primary_data:
  postgres_queue_data:

networks:
  backend:
